Pada pelajaran yang lepas kita sudah tahu serba sedikit tentang perbezaan tatasusunan dan senarai.
Untuk pelajaran kali ini kita akan lebih fokus kepada tatasusunan.
Tatasusunan sering digunakan dalam matematik berangka yang banyak melibatkan vektor dan matriks.
Suatu vektor boleh jadi vektor baris (*row vector*) atau vektor lajur (*column vector*).

Mari kita cuba bina vektor baris $\mathbf{A}$ dahulu.
\begin{equation}
\mathbf{A} = \begin{pmatrix}1 & 5 & 10 & 20 & 50 & 100 \end{pmatrix}
\end{equation}

In [1]:
from numpy import *
A = array([1, 5, 10, 20, 50, 100])
print(A)

[  1   5  10  20  50 100]


Vektor lajur $\mathbf{B}$.
\begin{equation}
\mathbf{B} = \begin{pmatrix}1 \\ 5 \\ 10 \\ 20 \\ 50 \\ 100 \end{pmatrix}
\end{equation}


In [2]:
B = array([[1],
         [5],
         [10],
         [20],
         [50],
         [100]])
print(B)

[[  1]
 [  5]
 [ 10]
 [ 20]
 [ 50]
 [100]]


Atau boleh juga kita ubah vektor baris $\mathbf A$ menjadi vektor lajur dengan menggunakan fungsi **namapembolehubah.reshape((bilanganbaris, bilanganlajur))**.

In [3]:
BLagi = A.reshape((6,1))
print(BLagi)

[[  1]
 [  5]
 [ 10]
 [ 20]
 [ 50]
 [100]]


Matriks $\mathbf{C}$ bersaiz 2 kali 2
\begin{equation}
\mathbf{C} =
\begin{pmatrix} 
1 & 2 \\
3 & 4
\end{pmatrix}
\end{equation}


In [4]:
C = array([
        [1, 2],
        [3, 4]
    ])
print(C)

[[1 2]
 [3 4]]


Matriks $\mathbf{D}$ bersaiz 3 kali 3
\begin{equation}
\mathbf{C} =
\begin{pmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
\end{equation}

In [5]:
D = array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Terdapat beberapa fungsi terbina yang berguna untuk operasi yang melibatkan vektor dan matriks.
Salah satunya yang telah kita gunakan sebentar tadi ialah fungsi **reshape**.
Berikut ialah senarai fungsi yang menarik untuk diterokai:
* reshape(namapembolehubah, (bilanganbaris, bilanganlajur)):  mengubah tatasusunan bernama **namapembolehubah** kepada suatu tatasusunan berbentuk bilanganbaris kali bilanganlajur.
* transpose(namapembolehubah): mengtransposisikan tatasusunan bernama **namapembolehubah**
* flipud(namapembolehubah): menterbalikkan tatasusunan bernama **namapembolehubah** dari baris atas ke baris bawah.
* fliplr(namapembolehubah):menterbalikkan tatasusunan bernama **namapembolehubah** dari lajur paling kiri ke lajur paling kanan.
* rot90(namapembolehubah): membuat putaran 90 darjah terhadap tatasusunan bernama **namapembolehubah**
* shape(namapembolehubah): memaklumkan bentuk atau saiz tatasusunan bernama **namapembolehubah**
* size(namapembolehubah): memaklumkan jumlah keseluruhan elemen yang terkandung di dalam tatasusunan bernama **namapembolehubah**

In [6]:
reshape(D, ((1,9)))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
transpose(D)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
flipud(D)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [9]:
fliplr(D)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [10]:
rot90(D)

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [11]:
size(D)

9

In [12]:
shape(D)

(3, 3)

Tatasusunan yang diberikan dalam pelajaran kita hanya yang berbentuk kecil sahaja akan tetapi apabila kita mengaturcara untuk kaedah berangka, tatasusunan yang terlibat ialah berbentuk besar sebagai contoh 1000 kali 1000. Adakalanya kita tidak mahu melihat semua elemen. Kita hanya mahu lihat suatu/beberapa elemen, baris atau lajur sahaja. 
Kita boleh berbuat demikian dengan mengakses posisi elemen, baris atau lajur yang kita mahukan sahaja.
Di dalam Python, pengiraan posisi bermula dengan 0.

Contohnya, ini ialah posisi untuk tatasusunan asal $\mathbf D$
\begin{equation}
\mathbf{D} = \begin{pmatrix} \textrm{D}[0,0] & \textrm{D}[0,1] & \textrm{D}[0,2] \\
                            \textrm{D}[1,0] & \textrm{D}[1,1] & \textrm{D}[1,2] \\
                            \textrm{D}[2,0] & \textrm{D}[2,1] & \textrm{D}[2,2]
             \end{pmatrix}
\end{equation}

Mari kita cuba mengakses elemen di posisi 0,0.

In [13]:
D[0,0]

1

Kita cuba pula mengakses elemen 0,0 dan 1,0 sekaligus.

In [14]:
D[0:2,0]

array([1, 4])

Perhatikan nombor yang dipanggil di dalam ruang untuk posisi baris. Ianya ditulis 0:2 bermakna bermula dengan baris di posisi 0 dan berakhir sebelum posisi 2 (iaitu posisi 1).

Selain itu, kita juga boleh menukar salah satu atau beberapa elemen yang terkandung di dalam suatu tatasusunan.
Sebagai contoh, jika kita mahu menukar elemen pertama dalam tatasusunan D dari 1 kepada 100, kita boleh berbuat demikian dengan memberi arahan **namapembolehubah [posisibaris,posisilajur] = nilaibaru**.

In [15]:
D[0,0] = 100
print(D)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


Mari kita cuba ubah ketiga-tiga elemen di dalam baris 2 menjadi [10 11 12].

In [16]:
D[2,:] = array([10, 11, 12])
print(D)

[[100   2   3]
 [  4   5   6]
 [ 10  11  12]]


Tanda : sahaja digunakan untuk membaca setiap posisi yang ada.
Bagaimana pula kalau kita cuba ubah kesemua elemen dalam baris 2?

In [17]:
D[:,2] = array([13,14,15])
print(D)

[[100   2  13]
 [  4   5  14]
 [ 10  11  15]]


Pelbagai operasi boleh kita jalankan pada tatasusunan. Mari kita terokai bersama.

In [18]:
Z = array([[4,3,2],[9,8,7],[6,5,1]])
print(Z)

[[4 3 2]
 [9 8 7]
 [6 5 1]]


In [19]:
D + Z

array([[104,   5,  15],
       [ 13,  13,  21],
       [ 16,  16,  16]])

In [20]:
D - Z

array([[96, -1, 11],
       [-5, -3,  7],
       [ 4,  6, 14]])

In [21]:
D * Z

array([[400,   6,  26],
       [ 36,  40,  98],
       [ 60,  55,  15]])

Untuk operasi darab, walaupun tatasusunan kita kelihatan seperti matriks tetapi pengiraan yang dijalankan ialah pendaraban elemen, bukan pendaraban dua matriks. Jika kita mahukan hasil darab dua matriks, kita hendaklah menggunakan fungsi **dot**.

In [22]:
dot(D,Z)

array([[496, 381, 227],
       [145, 122,  57],
       [229, 193, 112]])

Untuk mencari matriks songsang, kita boleh menggunakan fungsi tersedia **inv(namapembolehubah)**.

In [23]:
from numpy.linalg import inv
inv(D)

array([[ 0.01010489, -0.01445382,  0.00473267],
       [-0.0102328 , -0.17523663,  0.17242261],
       [ 0.00076746,  0.13814275, -0.0629317 ]])

Wah. Banyak juga yang telah kita pelajari tentang tatasusunan. Insha Allah selepas ini kita akan pelajari cara-cara untuk memplot graf dalam Python. 